### PR TITLE
Specifying platform for OpenWrt

### PR DESCRIPTION
**Pull request by smoe**

### CODE REVIEW

**Comment by smoe** [comment]
Looks nice but does not work for me. Weird.

**Comment by N30dG** [comment]
But for me :)
```
<platform>arm-openwrt-linux-muslgnueabi</platform>
<alt_platform>arm-mvebu-router-openwrt-muslgnueabi</alt_platform>
```

**Comment by smoe** [comment]
How supercool is that. Great! I feel like I am particularly happy about the alt-platform - should that be the main one? I also found client/hostinfo_unix.cpp to be of potential relevance for extra patches that address OpenWrt - but since this is now apparently working - happy!

**Comment by smoe** [comment]
I just found these files in /etc that BOINC could learn to find and interpret. How do these look for you?
```
root@OpenWrt:/mnt/boincdev/boinc-client_release-7.16-7.16.5# cat /etc/board.json
{
	"model": {
		"id": "innotek-gmbh-virtualbox",
		"name": "innotek GmbH VirtualBox"
	},
	"network": {
		"lan": {
			"ifname": "eth0",
			"protocol": "static"
		}
	}
}
root@OpenWrt:/mnt/boincdev/boinc-client_release-7.16-7.16.5# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r12659-ed7751f968'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r12659-ed7751f968'
DISTRIB_TAINTS=''
root@OpenWrt:/mnt/boincdev/boinc-client_release-7.16-7.16.5# cat /etc/openwrt_version
r12659-ed7751f968
root@OpenWrt:/mnt/boincdev/boinc-client_release-7.16-7.16.5# cat /etc/device_info
DEVICE_MANUFACTURER='OpenWrt'
DEVICE_MANUFACTURER_URL='https://openwrt.org/'
DEVICE_PRODUCT='Generic'
DEVICE_REVISION='v0'
```

**Pull request merged**
